# Generated by Django 4.0.3 on 2022-04-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=20, max_length=20),
        ),
    ]
