# Generated by Django 4.0.3 on 2022-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budzetapp', '0002_alter_transaction_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data transakcji'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
